### ISSUE TITLE
Does it support 4.5 Framework?

### ISSUE THREAD

**Issue by slavapvf** [Lenny32/ThenInclude#1]
hello, tried to use it in 4.5 Framework, but wasn't able to install

**Comment by Lenny32** [comment]
It should be working. I just put a restriction on the framework for the Nuget package. I would recommend to use the framework 4.5.2 or if you cannot, you can copy the source code directly in your solution / project.

- HelperQueryInclude.cs
- IIncludableQueryable.cs
- IncludableQueryable.cs
- QueryInclude.cs

Just a reminder, the framework 4.5 is not supported by Microsoft January since 2016 ([link](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/))

**Comment by slavapvf** [comment]
Thanks, I wrote because EF 6.3.1 supports 4.5.
